const { StyleSheet } = require('react-native');

export const styles = StyleSheet.create({
    body: {
        width: '100%',
        height: '100%',
        backgroundColor: '#FFF',
    },
    bodyStart: {
        width: '100%',
        height: 60,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    textMenu: {
        color: '#000000',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 24,
        lineHeight: 36,
    },
    container: {
        width: 36,
        height: 36,
        backgroundColor: '#eeeeee',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
    },
    imgMenu: {
        width: 24,
        height: 24,
    },
    container1: {
        width: '94%',
        height: 75,
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        padding: 16,
        borderRadius: 6,
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 10,
        },
        elevation: 10,
        marginTop: 10,
    },
    imgAvatar: {
        width: 45,
        height: 45,
        borderRadius: 100,
        alignSelf: 'center',
    },
    textName: {
        width: 'auto',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 16,
        color: '#000000',
        marginLeft: 16,
        alignSelf: 'center',
    },
    container2: {
        width: 36,
        height: 36,
        alignSelf: 'center',
        justifyContent: 'center',
        backgroundColor: '#f3f6f4',
        borderRadius: 100,
        marginLeft: 'auto',
    },
    userIcon: {
        alignSelf: 'center',
    },
    bodyBtnIcon: {
        width: '100%',
        height: 60,
        marginTop: 30,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        // alignItems: 'center',
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    btnIcon: {
        width: 150,
        height: 60,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        marginHorizontal: 10,
        marginVertical: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 10,
        },
        elevation: 10,
        marginTop: 10,
    },
    text0: {
        color: '#000000',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 14,
        lineHeight: 24,
        textAlign: 'center',
    },
    imgIcon: {
        width: 24,
        height: 24,
    },
    imgIconMmr: {
        width: 24,
        height: 24,
        // quay cả hình sang trái
        transform: [{ rotate: '180deg' }],
    },
    btnHelp: {
        width: '100%',
        height: 60,
        // backgroundColor: '#eeeeee',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#E5E5E5',
    },
    btnPrivacy: {
        width: '100%',
        height: 60,
        // backgroundColor: '#eeeeee',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#E5E5E5',
        flexDirection: 'row',
    },
    imgSettings: {
        width: 30,
        height: 30,
        position: 'absolute',
        left: '5%',
    },
    btnSecurity: {
        width: '100%',
        height: 60,
        // backgroundColor: '#eeeeee',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#E5E5E5',
    },
    btnLogout: {
        width: '90%',
        height: 45,
        backgroundColor: '#eeeeee',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        borderRadius: 6,
        borderTopWidth: 1,
        borderTopColor: '#E5E5E5',
        marginTop: 10,
    },
    textbtn1: {
        color: '#000000',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 24,
        position: 'absolute',
        left: '15%',
    },
    textLogout: {
        color: '#000000',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 16,
        lineHeight: 24,
    },
    confirmLogoutContainer: {
        position: 'absolute',
        bottom: 240,
        width: '90%',
        backgroundColor: '#FFFFFF',
        padding: 18,
        borderTopWidth: 1,
        borderTopColor: '#E5E5E5',
        alignSelf: 'center',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 10,
        },
        elevation: 10,
    },
    confirmLogoutText: {
        fontFamily: 'Poppins',
        fontSize: 16,
        marginBottom: 10,
        textAlign: 'center',
        color: '#000000',
    },
    confirmLogoutButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    confirmLogoutButton: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 10,
        marginHorizontal: 5,
        borderRadius: 5,
        backgroundColor: '#E5E5E5',
    },
    confirmLogoutButtonText1: {
        fontFamily: 'Poppins',
        fontSize: 16,
        color: '#000000',
    },
    confirmLogoutButtonText2: {
        fontFamily: 'Poppins',
        fontSize: 16,
        color: 'red',
    },
    setting: {
        width: '100%',
        position: 'absolute',
        bottom: 15,
    }
});
