const {StyleSheet} = require('react-native')

export const styles = StyleSheet.create({
    btnBack: {
        width: '100%',
        height: 50,
        backgroundColor: '#22b6c0',
        flexDirection: 'row',
        alignItems: 'center',   
    },
    imgBack: {
        // width: 24,
        // height: 24,
        marginLeft: 10,
    },
    txtBack: {
        color: '#FFFFFF',
        fontSize: 18,
        marginLeft: 10,
    },
    bodyAccount: {
        width: '100%',
        height: 'auto',
        backgroundColor: '#FFFFFF', 
    },
    txtAccount: {
        color: '#22b6c0',
        fontSize: 18,
        marginLeft: 15,
        marginTop: 10,
    },
    userFrame: {
        width: '92.5%',
        height: 75,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        elevation: 2,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        marginTop: 10,
        marginLeft: 15,
    },
    imgAvatar: {
        width: 45,
        height: 45,
        borderRadius: 30,
        marginLeft: 10,
    },
    txtUser: {
        fontSize: 16,
        position: 'absolute',
        left: 90,
        top: 15,
    },
    txtName: {
        color: '#000000',
        fontSize: 18,
        position: 'absolute',
        left: 90,
        top: 36,
    },
    imgNext: {
        width: 18,
        height: 18,
        position: 'absolute',
        right: 10,
    },
    emailFrame: {
        width: '100%',
        height: 75,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
        marginTop: 10,
    },
    imgEmail: {
        width: 30,
        height: 30,
        marginLeft: 15,
    },
    txtEmail: {
        fontSize: 18,
        position: 'absolute',
        left: 60,
        top: 15,
        color: '#000000',
    },
    txtEmail2: {
        fontSize: 16,
        position: 'absolute',
        left: 60,
        top: 36,
    },
    imgNext2: {
        width: 18,
        height: 18,
        position: 'absolute',
        right: 15,
    },
    qrFrame: {
        width: '100%',
        height: 60,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
        marginTop: 10,
    },
    txtQr: {
        fontSize: 18,
        position: 'absolute',
        left: 60,
        top: 15,
        color: '#000000',
    },
    bodySecurity: {
        width: '100%',
        height: 'auto',
        backgroundColor: '#FFFFFF',
        marginTop: 15,
    },
});