const { StyleSheet } = require('react-native');

export const styles = StyleSheet.create({
    profileFrame: {
        width: '100%',
        height: '50%',
    },
    imgCover: {
        width: '100%',
        height: 210,
        position: 'absolute',
    },
    imgAvatar: {
        width: 75,
        height: 75,
        borderRadius: 100,
        position: 'absolute',
        top: 120,
        left: 15,
        padding: 15,
    },
    btnBack: {
        alignItems: 'center',
        position: 'absolute',
        padding: 10,
    },
    editFrame: {
        width: '100%',
        height: 270,
        position: 'absolute',
        backgroundColor: '#FFFFFF',
        marginTop: 210,
    },
    txt1: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 20,
        color: '#000000',
        padding: 15,
    },
    Frame: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
    },
    txtTtcn: {
        width: 90,
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 16,
        paddingLeft: 10,
    },
    txtTtcn1: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 16,
        paddingLeft: 30,
        color: '#000000',
        // justifyContent: 'center',
        // textAlign: 'center',
    },
    btnEdit: {
        width: 240,
        height: 60,
        backgroundColor: '#22b6c0',
        marginTop: 12,
        borderRadius: 30,
        justifyContent: 'center',
        alignSelf: 'center',
    },
    txtEdit: {
        color: '#FFFFFF',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 24,
        textAlign: 'center',
    },
    modalContainerEdit: {
        position: 'absolute',
        width: '100%',
        height: '100%',
        backgroundColor: '#edebeb',
        bottom: 0,
    },
    FrameEditIfm: {
        position: 'absolute',
        width: '100%',
        height: 330,
        backgroundColor: '#FFFFFF',
    },
    btnCancelEdit: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#22b6c0',
        padding: 10,
    },
    txtCancelEdit: {
        color: '#FFFFFF',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 24,
        marginLeft: 16,
    },
    txtInputName: {
        flexDirection: 'row',
        width: '100%',
        height: 60,
        backgroundColor: '#FFFFFF',
        textAlign: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
        fontSize: 18,
        color: '#000000',
    },
    imgEdit: {
        width: 30,
        height: 30,
        position: 'absolute',
        right: 10,
        top: 15,
    },
    txtInputDate: {
        width: '100%',
        height: 60,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
        justifyContent: 'center',
    },
    dateInput: {
        fontSize: 18,
        color: '#000000',
        textAlign: 'center',
    },
    CheckboxFrame: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 15,
    },
    CheckBox: {
        width: 30,
        height: 30,
        margin: 6,
        marginLeft: 45,
    },
    txtCheckbox: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 24,
        color: '#000000',
    },
    btnSave: {
        width: 240,
        height: 60,
        backgroundColor: '#22b6c0',
        marginTop: 15,
        borderRadius: 30,
        justifyContent: 'center',
        alignSelf: 'center',
    },
    txtSave: {
        color: '#FFFFFF',
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 24,
        textAlign: 'center',
    },
});