import { StyleSheet } from 'react-native';
export default styles = StyleSheet.create({
    viewlogin: {
        width: '100%',
        height: '10%',
        justifyContent: 'center',
        alignItems: 'center',
        top: '3%',
      },
      register: {
        color: '#d7bd1e',
        fontSize: 17,
      },
      acc: {
        position: 'absolute',
        bottom: 20,
        width: '100%',
        height: 'auto',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
      },
      txt3: {
        color: 'black',
        fontSize: 20,
        fontWeight: 'bold',
      },
      button: {
        width: '90%',
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#3cc8bf',
        borderRadius: 30,
        top: '2%',
      },
      forgot: {
        width: '100%',
        height: 'auto',
        justifyContent: 'center',
        alignItems: 'flex-start',
        marginLeft: '10%',
      },
      icon: {
        marginRight: 10,
      },
      input: {
        flex: 1,
        height: 70,
        paddingLeft: '5%',
        paddingRight: '5%',
        color: 'grey',
        fontSize: 17,
      },
      viewinput: {
        flexDirection: 'row',
        width: '90%',
        height: 70,
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '5%',
        borderWidth: 1.5,
        borderColor: 'grey',
        borderRadius: 25,
      },
      viewif: {
        width: '100%',
        height: '10%',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        marginBottom: '5%',
      },
      txt1: {
        color: 'black',
        fontSize: 17,
      },
      txt2: {
        color: '#0ad3c7',
        fontSize: 17,
      },
      txt: {
        color: 'black',
        fontSize: 25,
        fontWeight: 'bold',
      },
      logo: {
        width: '70%',
        height: '90%',
        justifyContent: 'center',
        alignItems: 'center',
      },
      viewlogo: {
        width: '100%',
        height: '10%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '-40%',
      },
      container: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
      },
});